//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubrania_Nowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        public int Id { get; set; }
        public string Mark { get; set; }
        public string Size { get; set; }
        public string Colour { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public int Price_RL { get; set; }
        public int Agreement_Id { get; set; }
        public bool Sold { get; set; }
        public string Box { get; set; }
    
        public virtual Agreements Agreements { get; set; }
    }
}
